[View in Colaboratory](https://colab.research.google.com/github/LearnCoding199x/learning_AI/blob/master/Linear_tf_data.ipynb)

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import math

In [0]:
def gen(num_train=1000,num_feature=5):
    gen_graph =  tf.Graph()
    with gen_graph.as_default():
        w = tf.random_normal([num_feature,1])
        b = tf.Variable(np.random.rand())
        x = tf.random_normal(shape=[num_train,num_feature])
        y = tf.matmul(x,w)+b
    with tf.Session(graph=gen_graph) as sess:
        sess.run(tf.global_variables_initializer())
        x,y,w,b =sess.run([x,y,w,b])
        return x,y,w,b

In [0]:
# X : matrix mxn
# w : matrix nx1
# y : matrix mx1
# b : scalar
def linreg(x,y,batch_size=64,lr=0.01,epoches=1000):
    num_train = x.shape[0]
    num_feature = x.shape[1]
    losses = []
    dataset = tf.data.Dataset.from_tensor_slices((x,y)).batch(batch_size = 1)
    iter = dataset.make_initializable_iterator()
    features,label = iter.get_next()
    w = tf.Variable(tf.zeros([num_feature,1]))
    b = tf.Variable(np.random.rand())
    x_t = tf.placeholder(tf.float32,shape=[None,num_feature])
    y_true = tf.placeholder(tf.float32,shape=[None,1])
    y_t = tf.matmul(x_t,w)+b
    loss = 0.5 * tf.reduce_mean(tf.square(y_t-y_true),0)
    update_w = w.assign(tf.subtract(w,tf.matmul(tf.transpose(x_t),(y_t-y_true))*(1.0/num_train)*lr))
    update_b = b.assign(tf.subtract(b,tf.reduce_mean(y_t-y_true)*lr))
    with tf.Session(graph=tf.get_default_graph()) as sess:
        sess.run(tf.global_variables_initializer())
        for epoch in range(epoches):
          sess.run(iter.initializer)
          while True:
            try:
              tempx,tempy = sess.run(iter.get_next())
              _loss,_u,_b=sess.run([loss,update_w,update_b],feed_dict={x_t :tempx ,y_true :tempy })
            except tf.errors.OutOfRangeError:
              break
          if epoch%50==0:
              print("Epoch {} : Loss {}".format(epoch,_loss))
          losses.append(_loss)
        
    plt.plot(losses)
    plt.show()
    print('Prediction w ',_w)
    print('Prediction b ',_b)

In [21]:
x,y,w,b=gen()
print(x[0:10],y[0:10])
linreg(x,y)
print('Real w values ',w)
print('Real b values ',b)

[[ 2.201674   -0.25700027 -0.5904602   0.5821305  -0.8448961 ]
 [-0.74041027  1.4593123   1.0888062  -0.35541314  1.6235191 ]
 [ 0.45423862  0.232244    0.6073674  -1.3129628  -0.80409646]
 [ 1.1965137  -0.20646189  1.7856876   2.221029   -0.4622544 ]
 [ 0.96561664  1.1651032   2.6886451   0.2760372  -0.04691726]
 [ 1.6454763  -0.9880016  -1.0046299   0.2898077   0.56000113]
 [-0.91026956 -0.5247632   0.31135184  1.1435769   0.12882729]
 [ 0.0134046   0.0047617   0.29343703 -0.04292635  0.90151983]
 [ 0.73690325  2.3109527  -1.949495    1.6185482   1.2647485 ]
 [ 1.392487    0.9614684   1.3102177   0.4805222  -1.3323667 ]] [[ 0.6945953 ]
 [-1.7778938 ]
 [ 2.1346338 ]
 [ 0.30122635]
 [-0.33270985]
 [ 1.7881494 ]
 [ 0.95500445]
 [ 0.6983636 ]
 [-6.987107  ]
 [-0.47446173]]
[[ 2.201674   -0.25700027 -0.5904602   0.5821305  -0.8448961 ]] [[0.6945953]]
[[-0.74041027  1.4593123   1.0888062  -0.35541314  1.6235191 ]] [[-1.7778938]]
[[ 0.45423862  0.232244    0.6073674  -1.3129628  -0.80409646

KeyboardInterrupt: ignored

In [15]:
np.random.sample((100,2)).shape[0]

100